NUM_EPOCHS: 10
BATCH_SIZE: 32
NUM_STEPS_PER_EPISODE: 128
NUM_TOTAL_STEPS: 50000
SCENES:
  - minival/00800-TEEsavR23oF
LEARNING_RATE: 0.0001
DISCOUNT_FACTOR: 0.99
ENTROPY_COEFFICIENT: 0.001
VALUE_LOSS_COEFFICIENT: 0.5
